INSERT INTO USER VALUES (1, 'demo');

INSERT INTO TASK_CORE(ID, PRIORITY) VALUES (1, 1);
INSERT  INTO TASK (TASK_ID, TITLE, COMPLETE, USER_ID) VALUES (1, 'todo-item-one', FALSE, 1);

INSERT INTO TASK_CORE(ID, PRIORITY) VALUES (2, 2);
INSERT  INTO TASK (TASK_ID, TITLE, COMPLETE, USER_ID) VALUES (2, 'todo-item-two', TRUE, 1);

INSERT INTO TASK_CORE(ID, PRIORITY) VALUES (3, 3);
INSERT  INTO TASK (TASK_ID, TITLE, COMPLETE, USER_ID) VALUES (3, 'todo-item-three', FALSE, 1);
