INSERT INTO USERS VALUES (1, 'admin');

INSERT INTO TODO (COMPLETED, DESCRIPTION, TITLE, USER_ID) VALUES ('TRUE', 'First item', '1 item', 1);

INSERT INTO TODO (COMPLETED, DESCRIPTION, TITLE, USER_ID) VALUES ('FALSE', 'Second item', '2 item', 1);

INSERT INTO TODO (COMPLETED, DESCRIPTION, TITLE, USER_ID) VALUES ('FALSE', 'Third item', '3 item', 1);

INSERT INTO TODO (COMPLETED, DESCRIPTION, TITLE, USER_ID) VALUES ('FALSE', 'Fourth item', '4 item', 1);
