INSERT INTO USER VALUES (1, 'admin');

INSERT INTO TASK_CORE(ID, COMPLETE, PRIORITY) VALUES (1, TRUE, 1);
INSERT  INTO TASK (TASK_ID, DESCRIPTION, TITLE, USER_ID) VALUES (1, 'First item', 'todo-item-one', 1);

INSERT INTO TASK_CORE(ID, COMPLETE, PRIORITY) VALUES (2, FALSE, 2);
INSERT  INTO TASK (TASK_ID, DESCRIPTION, TITLE, USER_ID) VALUES (2, 'Second item', 'todo-item-two', 1);

INSERT INTO TASK_CORE(ID, COMPLETE, PRIORITY) VALUES (3, TRUE, 3);
INSERT  INTO TASK (TASK_ID, DESCRIPTION, TITLE, USER_ID) VALUES (3, 'Third item', 'todo-item-three', 1);
