DROP TABLE IF EXISTS users, todo;

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    username VARCHAR(32)
);

CREATE TABLE todo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    title       VARCHAR(32),
    description VARCHAR(255),
    user_id     BIGINT REFERENCES users
);
