DROP TABLE IF EXISTS users, todo;

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT todo_pkey
            PRIMARY KEY,
    username VARCHAR(32)
);

CREATE TABLE todo
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pkey
            PRIMARY KEY,
    title       VARCHAR(32),
    description VARCHAR(255),
    user_id     BIGINT REFERENCES users
);

ALTER TABLE users
    OWNER TO idea;

ALTER TABLE todo
    OWNER TO idea;
